# Generated by Django 3.2.25 on 2024-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241021_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='available', max_length=20),
        ),
    ]
