# Generated by Django 3.2.25 on 2024-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241102_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('merchant', 'merchant'), ('influencer', 'influencer'), ('admin', 'admin')], default='influencer', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
